### ISSUE TITLE
記事を書いてみる

### ISSUE THREAD

**Issue by Abebe123000** [Abebe123000/blog-starter-app#3]

**Comment by Abebe123000** [comment]
確かめたほうがいいこと
- リンクとかを貼ることができるのか
  - 内部リンク
  - 外部リンク
- 画像を貼ることができるのか

**Comment by Abebe123000** [comment]
```
title: "Learn How to Pre-render Pages Using Static Generation with Next.js"
excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. At imperdiet dui accumsan sit amet nulla facilities morbi tempus."
coverImage: "/assets/blog/hello-world/cover.jpg"
date: "2020-03-16T05:35:07.322Z"
author:
  name: Tim Neutkens
  picture: "/assets/blog/authors/tim.jpeg"
ogImage:
  url: "/assets/blog/hello-world/cover.jpg"
```

この部分はどうするのか
変えられるのか？
